"""PR-1 red tests — REQ-19 npm / yarn / pnpm edge emission.

Each lockfile format yields one DepEdge per parent→child dependency
relationship. Same package at distinct versions in different lockfile
paths produces distinct edges.
"""
from __future__ import annotations

import json

import pytest

from scarno.analysers.javascript import dep_file_parser as _npm


# ── TA-207 ──────────────────────────────────────────────────────────────────


@pytest.mark.requirement("FR-193")
def test_npm_package_lock_v3_emits_distinct_versions(tmp_path):
    """TA-207 — package-lock.json v3 with two paths declaring scheduler at
    different versions emits two distinct edges.
    """
    pkg_root = tmp_path / "project"
    pkg_root.mkdir()
    (pkg_root / "package.json").write_text(
        json.dumps({"name": "app", "version": "1.0.0", "dependencies": {"react": "^18"}})
    )
    (pkg_root / "package-lock.json").write_text(
        json.dumps(
            {
                "name": "app",
                "version": "1.0.0",
                "lockfileVersion": 3,
                "packages": {
                    "": {
                        "name": "app",
                        "version": "1.0.0",
                        "dependencies": {"react": "18.2.0"},
                    },
                    "node_modules/react": {
                        "version": "18.2.0",
                        "dependencies": {"scheduler": "0.23.0"},
                    },
                    "node_modules/legacy-shim": {
                        "version": "1.0.0",
                        "dependencies": {"scheduler": "0.23.2"},
                    },
                    "node_modules/scheduler": {"version": "0.23.0"},
                    "node_modules/legacy-shim/node_modules/scheduler": {
                        "version": "0.23.2"
                    },
                },
            }
        )
    )

    result = _npm.parse_all_npm_dependency_files(  # type: ignore[call-arg]
        str(pkg_root)
    )
    # New REQ-19 contract: every NpmParseResult / equivalent carries
    # ``edges: list[DepEdge]``. We probe for both — the API may expose the
    # edges directly OR via a helper.
    edges = getattr(result, "edges", None)
    if edges is None:
        # Alternate API shape — gather from the parser's returned tuple/list.
        edges = []
        if isinstance(result, tuple):
            for item in result:
                if isinstance(item, list) and item and hasattr(item[0], "child"):
                    edges = item
                    break
    scheduler_versions = sorted(
        e.declared_version for e in edges if e.child == "scheduler"
    )
    assert scheduler_versions == ["0.23.0", "0.23.2"], (
        "Expected two distinct scheduler edges; "
        f"got {scheduler_versions!r}"
    )


# ── TA-208 ──────────────────────────────────────────────────────────────────


@pytest.mark.requirement("FR-193")
def test_yarn_lock_v1_partial_parse_skips_malformed(tmp_path):
    """TA-208 — yarn.lock v1 with one valid + one malformed entry: valid is
    emitted as an edge, malformed dropped with a sanitised note.
    """
    pkg_root = tmp_path / "project"
    pkg_root.mkdir()
    (pkg_root / "package.json").write_text(
        json.dumps({"name": "app", "version": "1.0.0", "dependencies": {"good-lib": "^1"}})
    )
    (pkg_root / "yarn.lock").write_text(
        '# THIS IS AN AUTOGENERATED FILE\n'
        'good-lib@^1:\n'
        '  version "1.2.3"\n'
        '\n'
        'malformed-entry@^9  # missing colon and version line below\n'
        '  this line is junk and lacks a version key\n'
    )

    result = _npm.parse_all_npm_dependency_files(  # type: ignore[call-arg]
        str(pkg_root)
    )
    edges = getattr(result, "edges", None) or []
    children = {e.child for e in edges}
    assert "good-lib" in children, "valid yarn entry must produce an edge"
    assert "malformed-entry" not in children, (
        "malformed yarn entry must NOT produce an edge"
    )


# ── TA-209 ──────────────────────────────────────────────────────────────────


@pytest.mark.requirement("FR-193")
def test_pnpm_lockfile_v6_emits_edges(tmp_path):
    """TA-209 — pnpm-lock.yaml v6 with at least one dependency edge."""
    pkg_root = tmp_path / "project"
    pkg_root.mkdir()
    (pkg_root / "package.json").write_text(
        json.dumps({"name": "app", "version": "1.0.0", "dependencies": {"react": "18.2.0"}})
    )
    (pkg_root / "pnpm-lock.yaml").write_text(
        "lockfileVersion: '6.0'\n"
        "\n"
        "dependencies:\n"
        "  react:\n"
        "    specifier: 18.2.0\n"
        "    version: 18.2.0\n"
        "\n"
        "packages:\n"
        "  /react@18.2.0:\n"
        "    resolution: {integrity: sha512-XYZ}\n"
        "    dependencies:\n"
        "      loose-envify: 1.4.0\n"
        "  /loose-envify@1.4.0:\n"
        "    resolution: {integrity: sha512-ABC}\n"
    )

    result = _npm.parse_all_npm_dependency_files(  # type: ignore[call-arg]
        str(pkg_root)
    )
    edges = getattr(result, "edges", None) or []
    children = {e.child for e in edges}
    assert "loose-envify" in children, (
        "pnpm-lock.yaml v6 transitive edge missing"
    )
